### ISSUE TITLE
Branch 2.0 Not Tested

### ISSUE THREAD

**Issue by ChinwalPrasad** [uisits/laravel-shibboleth#1]
@naishu @bneale35 @marishaS @tllos1 
Please test this branch:

## Steps to install:
- If you are already using prasad/laravel-shibboleth remove it from composer.json
- Edit and Update the laravel version to 5.8.* in composer.json file
- Run ``` composer update ```
- Run  ```composer require uisits/laravel-shibboleth:2.0.x-dev ```

 - Note: if you do not specify 2.0.x-dev Composer will pull version 1.0 of this package which only supports till Laravel 5.7.*

If you run into any issue please comment here, 
If you have any suggestions for the package or improvements please let me know and I will work on it.
Thanks for the help.

**Comment by naishu** [comment]
composer require uisits/laravel-shibboleth:2.0.x-dev isn't backward compatible. it fails on laravel 5.7

    - uisits/laravel-shibboleth 2.0.x-dev requires laravel/framework 5.8.* -> satisfiable by laravel/framework[5.8.x-dev].

**Comment by ChinwalPrasad** [comment]
@naishu 

I believe it is a good approach to keep the supported version separate from each other. For example check the Yajra/OCI-8 package. 

**Let me know if you think otherwise.**

Reason: You can edit and keep each version supporting laravel version separate.

Solution to above issue: 
Please check the below table for compatibility.

| uisits\laravel-shibboleth |  Laravel version |
--------------------------|-----------------|
|           1.0                           |          v 5.7           |
|           2.0                          |           v 5.8           |


Note: for Laravel v 5.6 Please use the uabookstores/laravel-shibboleth package.

**Comment by ChinwalPrasad** [comment]
Tested Successfully on Laravel 5.8.

Let me know if anyone faces any issues.
